import type { Metadata } from 'next';
import { Poppins } from 'next/font/google'; // Import font Poppins
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import { Toaster } from 'react-hot-toast';
import { Footer } from '@/components/footer/Footer';

const poppins = Poppins({
  variable: '--font-poppins', // Variabel CSS untuk digunakan di Tailwind atau global styles
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Sesuaikan dengan kebutuhan
});

export const metadata: Metadata = {
  title: 'Cyber Solid',
  description: 'Generated by Threemusketers',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
